//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class generalTime
    {
        public int Id { get; set; }
        public int AttractionId { get; set; }
        public int PeriodId { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int DayInWeek { get; set; }
    
        public virtual period period { get; set; }
        public virtual attraction attraction { get; set; }
    }
}
