//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class productToOrder
    {
        public int Id { get; set; }
        public Nullable<int> OrderAttractionId { get; set; }
        public int AttractionId { get; set; }
        public int Amount { get; set; }
        public System.TimeSpan FromHour { get; set; }
        public System.TimeSpan TillHour { get; set; }
        public bool Status { get; set; }
    
        public virtual orderAttraction orderAttraction { get; set; }
        public virtual attraction attraction { get; set; }
    }
}
